# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Ensure output is unbuffered
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Copy project files
COPY pyproject.toml uv.lock ./
COPY arxiv_mcp ./arxiv_mcp

# Install dependencies
RUN pip install --no-cache-dir .

# Default command to start the MCP server over stdio
CMD ["arxiv-paper-mcp"]
